# -*- coding: utf-8 -*-
"""extractCSV-JSON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-f8ZWASQuX2gzqkXC3VkweQbKEJYCi-
"""

# Extracting CSV file to JSON

import csv
import json

def csv_to_json(csv_file_path, json_file_path):
    data_dict = {}

    # Opening a CSV
    with open(csv_file_path, encoding = 'utf-8') as csv_file_handler:
        # This will automatically open the file and also move out of block
        # This is a good practice
        csv_reader = csv.DictReader(csv_file_handler)
 
        # Converting rows to dictionary
        for rows in csv_reader:
 
            # Assuming a column named 'Serial Number' as 'key'
            key = rows['Serial Number']
            data_dict[key] = rows
 
    # Opeing a JSON
    with open(json_file_path, 'w', encoding = 'utf-8') as json_file_handler:
        json_file_handler.write(json.dumps(data_dict, indent = 4)) # Using json.dumps
 
csv_file_path = input('Enter file path of the CSV file: ')
json_file_path = input('Enter file path of the JSON file: ')
 
csv_to_json(csv_file_path, json_file_path)

