# -*- coding: utf-8 -*-
"""extractCSV-df.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-f8ZWASQuX2gzqkXC3VkweQbKEJYCi-
"""

import pandas as pd
from pandas.core.frame import DataFrame

def extract(file_path: str) -> DataFrame:
    # Extract CSV from filepath and converts it to a Dataframe


    df = pd.read_csv(file_path)

    return df

