# -*- coding: utf-8 -*-
"""load_JSON_CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-f8ZWASQuX2gzqkXC3VkweQbKEJYCi-
"""

# Load JSON to CSV

import json
import csv

# Opening JSON file and loading the data

with open('yourFile.json') as json_file:
 data = json.load(json_file)

house_data = data['houses_details']

# now we will open a file for writing
data_file = open('data_file.csv', 'w')

# create the csv writer object
csv_writer = csv.writer(data_file)

# Counter variable used for writing
# headers to the CSV file
count = 0

for houses in house_data:
 if count == 0:

  # Writing headers of CSV file
  header = houses.keys()
  csv_writer.writerow(header)
  count += 1

 # Writing data of CSV file
 csv_writer.writerow(houses.values())

data_file.close()

