# -*- coding: utf-8 -*-
"""load_df_CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-f8ZWASQuX2gzqkXC3VkweQbKEJYCi-
"""

# Converting df to CSV

def load(df: DataFrame, save_path: str):
    
    # Writing dataframe to csv with to_csv
    df.to_csv(save_path, index=False)
    return

